name: docuchat_env

dependencies:
    - python=3.10.12
    - streamlit=1.36.0
    - cmake=3.27.9
    - packaging=24.1
    - pytesseract=0.3.10
    - tiktoken=0.7.0
    - einops=0.8.0
    - rank-bm25=0.2.2
    - llama-cpp-python<0.2.80
    - pillow_heif=0.17.0
    - pdf2image=1.17.0
    - requests=2.31.0
    - pip:
        - unstructured.pytesseract=0.3.12
        - unstructured-inference=0.7.24
        - unstructured=0.12.5 
        - tiktoken=0.7.0
        - streamlit=1.36.0        
        - rank-bm25=0.2.2        
        - pypdfium2=4.30.0      
        - pypdf=4.3.0
        - pillow_heif=0.17.0      
        - pikepdf=9.0.0        
        - pdfminer.six=20231228        
        - pdf2image=1.17.0               
        - langchain-text-splitters=0.2.2        
        - langchain-huggingface=0.0.3       
        - langchain-core=0.2.21        
        - langchain-community=0.2.7        
        - langchain-chroma=0.1.2     
        - langchain=0.2.9
        - huggingface-hub=0.23.5
        - einops=0.8.0
        - cmake=3.27.9
